FROM rocker/r-ver:4.3.2

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libgit2-dev \
    make \
    g++ \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN R -q -e "install.packages('pak', repos = sprintf('https://r-lib.github.io/p/pak/stable/%s/%s/%s', .Platform[['pkgType']], R.Version()[['os']], R.Version()[['arch']]))"

RUN R -q -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); \
    pak::pkg_install(c('testthat', 'data.table', 'jsonlite', 'yaml'))"

WORKDIR /repo

CMD ["Rscript", "/repo/tests/run.R"]
